version: '2'
services:
    api:
        build: api/.
        ports:
          - "5000:5000"
        depends_on:
          - postgres
    postgres:
        build: postgres/.
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=fiap123
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data