version: '2'
services:
    postgres:
        image: jasonthiago/postgres_galaticos
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=fiap123
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        deploy:
          replicas: 1
          mode: replicated
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    api:
        #image: gmartini97/galaticos
        #build: api/.
        image: jasonthiago/api_galaticos
        ports:
          - "5000:5000"
        depends_on:
          - postgres
        deploy:
          replicas: 1
        restart_policy:
          condition: on-failure