version: '2'
services:
    postgres:
        image: postgres:10
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=fiap123
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
        networks:
          vpcbr:
           ipv4_address: 10.5.0.5
    api:
        image: gmartini97/galaticos
        ports:
          - "5000:5000"
        depends_on:
          - postgres
        networks:
          vpcbr:
           ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1